// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GameStore.Models.Entities
{
    public partial class Ciudad
    {
        public Ciudad()
        {
            Persona = new HashSet<Persona>();
            Sucursal = new HashSet<Sucursal>();
        }

        public decimal Id { get; set; }
        public string Nombre { get; set; }
        public decimal IdProvincia { get; set; }

        public virtual Provincia IdProvinciaNavigation { get; set; }
        public virtual ICollection<Persona> Persona { get; set; }
        public virtual ICollection<Sucursal> Sucursal { get; set; }
    }
}