// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GameStore.Models.Entities
{
    public partial class Compra
    {
        public Compra()
        {
            DetalleDeCompra = new HashSet<DetalleDeCompra>();
        }

        public decimal Id { get; set; }
        public decimal IdPersona { get; set; }
        public decimal IdSucursal { get; set; }
        public string FacturaNumero { get; set; }
        public DateTime Fecha { get; set; }
        public decimal? Total { get; set; }

        public virtual Persona IdPersonaNavigation { get; set; }
        public virtual Sucursal IdSucursalNavigation { get; set; }
        public virtual ICollection<DetalleDeCompra> DetalleDeCompra { get; set; }
    }
}