// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GameStore.Models.Entities
{
    public partial class DetalleDeVenta
    {
        public decimal Id { get; set; }
        public decimal IdVenta { get; set; }
        public decimal IdJuego { get; set; }
        public decimal Precio { get; set; }
        public int Cantidad { get; set; }
        public decimal? Descuento { get; set; }

        public virtual Juego IdJuegoNavigation { get; set; }
        public virtual Venta IdVentaNavigation { get; set; }
    }
}