// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GameStore.Models
{
    public partial class Direccion
    {
        public Direccion()
        {
            Persona = new HashSet<Persona>();
            Sucursal = new HashSet<Sucursal>();
        }

        public decimal Id { get; set; }
        public string Calle { get; set; }
        public int Numero { get; set; }
        public string Ciudad { get; set; }
        public string CodigoPostal { get; set; }

        public virtual ICollection<Persona> Persona { get; set; }
        public virtual ICollection<Sucursal> Sucursal { get; set; }
    }
}