// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GameStore.Models
{
    public partial class Marca
    {
        public Marca()
        {
            Consola = new HashSet<Consola>();
        }

        public decimal Id { get; set; }
        public string Nombre { get; set; }

        public virtual ICollection<Consola> Consola { get; set; }
    }
}