// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GameStore.Models.Entities
{
    public partial class Persona
    {
        public Persona()
        {
            Compra = new HashSet<Compra>();
            Venta = new HashSet<Venta>();
        }

        public decimal Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public decimal IdTipoPersona { get; set; }
        public decimal IdTipoDocumento { get; set; }
        public string Documento { get; set; }
        public decimal IdTipoTelefono { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string Calle { get; set; }
        public string NumeroCalle { get; set; }
        public decimal IdCiudad { get; set; }
        public string CodigoPostal { get; set; }

        public virtual Ciudad IdCiudadNavigation { get; set; }
        public virtual TipoDocumento IdTipoDocumentoNavigation { get; set; }
        public virtual TipoPersona IdTipoPersonaNavigation { get; set; }
        public virtual TipoTelefono IdTipoTelefonoNavigation { get; set; }
        public virtual ICollection<Compra> Compra { get; set; }
        public virtual ICollection<Venta> Venta { get; set; }
    }
}