// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GameStore.Models.Entities
{
    public partial class Sucursal
    {
        public Sucursal()
        {
            Compra = new HashSet<Compra>();
            Venta = new HashSet<Venta>();
        }

        public decimal Id { get; set; }
        public string Nombre { get; set; }
        public string Calle { get; set; }
        public string Numero { get; set; }
        public decimal IdCiudad { get; set; }
        public string CodigoPostal { get; set; }

        public virtual Ciudad IdCiudadNavigation { get; set; }
        public virtual ICollection<Compra> Compra { get; set; }
        public virtual ICollection<Venta> Venta { get; set; }
    }
}