// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GameStore.Models
{
    public partial class Juegos
    {
        public decimal Id { get; set; }
        public decimal IdGenero { get; set; }
        public decimal IdConsola { get; set; }
        public int Stock { get; set; }

        public virtual Consola IdConsolaNavigation { get; set; }
        public virtual Genero IdGeneroNavigation { get; set; }
    }
}