// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GameStore.Models
{
    public partial class Compra
    {
        public Compra()
        {
            DetalleDeCompra = new HashSet<DetalleDeCompra>();
        }

        public decimal Id { get; set; }
        public decimal IdProveedor { get; set; }
        public DateTime Fecha { get; set; }
        public decimal? Total { get; set; }

        public virtual Proveedor IdProveedorNavigation { get; set; }
        public virtual ICollection<DetalleDeCompra> DetalleDeCompra { get; set; }
    }
}