// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GameStore.Models
{
    public partial class Sucursal
    {
        public Sucursal()
        {
            DetalleDeVenta = new HashSet<DetalleDeVenta>();
        }

        public decimal Id { get; set; }
        public string Nombre { get; set; }
        public decimal? IdDireccion { get; set; }

        public virtual Direccion IdDireccionNavigation { get; set; }
        public virtual ICollection<DetalleDeVenta> DetalleDeVenta { get; set; }
    }
}