// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GameStore.Models
{
    public partial class Venta
    {
        public Venta()
        {
            DetalleDeVenta = new HashSet<DetalleDeVenta>();
        }

        public decimal Id { get; set; }
        public decimal IdCliente { get; set; }
        public DateTime Fecha { get; set; }
        public decimal? Total { get; set; }

        public virtual Cliente IdClienteNavigation { get; set; }
        public virtual ICollection<DetalleDeVenta> DetalleDeVenta { get; set; }
    }
}